# -*- coding: utf-8 -*-
"""exp4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJz9r4Y37fkNyQ58Oy_I6CQ9KQllAZ3-
"""

import pandas as pd
import numpy as np
from scipy import stats

# Load dataset
df = pd.read_csv("diabetes.csv")

print("First 5 records:")
print(df.head())

print("\nShape of dataset:")
print(df.shape)

print("\nColumn names:")
print(df.columns)

# Divide data based on diabetes outcome
non_diabetic = df[df["Outcome"] == 0]
diabetic = df[df["Outcome"] == 1]

print("Non-diabetic patients:", len(non_diabetic))
print("Diabetic patients:", len(diabetic))

# Create age groups for Chi-square test
df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[20, 30, 40, 50, 60, 100],
    labels=["21-30", "31-40", "41-50", "51-60", "61+"]
)

print("\nAge group distribution:")
print(df["AgeGroup"].value_counts().sort_index())

# Sample mean
sample_mean = df["Glucose"].mean()

# Sample proportion
sample_proportion = df["Outcome"].mean()

print("Sample mean of Glucose:", sample_mean)

print("Sample proportion of diabetic patients:", sample_proportion)

print("Percentage of diabetic patients:", sample_proportion * 100)

# Confidence Interval for Mean

n = len(df)
mean = df["Glucose"].mean()
std = df["Glucose"].std()

confidence = 0.95
alpha = 1 - confidence

# t-critical value
t_critical = stats.t.ppf(1 - alpha / 2, df=n - 1)

# Margin of error
margin_error = t_critical * (std / np.sqrt(n))

lower_mean = mean - margin_error
upper_mean = mean + margin_error

print("95% Confidence Interval for Mean Glucose:")
print(lower_mean, "to", upper_mean)

# Confidence Interval for Proportion

p = df["Outcome"].mean()

# Z-critical value
z = stats.norm.ppf(1 - alpha / 2)

# Margin of error
margin_prop = z * np.sqrt((p * (1 - p)) / n)

lower_prop = p - margin_prop
upper_prop = p + margin_prop

print("95% Confidence Interval for Diabetic Proportion:")
print(lower_prop, "to", upper_prop)

print("\nPercentage CI:")
print(lower_prop * 100, "% to", upper_prop * 100, "%")

# One-sample t-test

t_stat, p_value = stats.ttest_1samp(
    df["Glucose"],
    popmean=120
)

print("One-Sample t-Test")
print("T-statistic:", t_stat)
print("P-value:", p_value)

# Two-sample t-test

t_stat, p_value = stats.ttest_ind(
    non_diabetic["Glucose"],
    diabetic["Glucose"],
    equal_var=False
)

print("Two-Sample t-Test")
print("T-statistic:", t_stat)
print("P-value:", p_value)
