# -*- coding: utf-8 -*-
"""exp1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K4Fr7R7JyNJPEXQFZ_eF8u5IzvqGgf_U
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv("diabetes[1].csv")

df.head()

df.tail(5)

df.shape

df.dtypes

df.info()

df.describe()

print("Mean")
print(df.mean())

print("\nMedian")
print(df.median())

print("\nVariance")
print(df.var())

print("\nStandard Deviation")
print(df.std())

df.isnull().sum()

columns = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

for col in columns:
    print(col, (df[col] == 0).sum())

plt.figure(figsize=(12, 8))
sns.boxplot(data=df)
plt.xticks(rotation=45)
plt.show()

df.hist(figsize=(12, 10))
plt.show()

plt.figure(figsize=(10, 8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.show()

sns.countplot(x="Outcome", data=df)
plt.title("Diabetes Outcome")
plt.show()

sns.histplot(df["Age"], kde=True)
plt.show()

sns.histplot(df["BMI"], kde=True)
plt.show()

sns.boxplot(x="Outcome", y="BMI", data=df)
plt.show()

sns.pairplot(df, hue="Outcome")
plt.show()
