# -*- coding: utf-8 -*-
"""exp2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13p4I3GZWhSHF0kIBeRTv81EKMl5NCLnP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("diabetes.csv")
df.head()

df.tail(5)

df.shape

df.dtypes

df.info()

df.describe()

print("Mean")
print(df.mean())
print("\nMedian")
print(df.median())
print("\nVariance")
print(df.var())
print("\nStandard Deviation")
print(df.std())
