# -*- coding: utf-8 -*-
"""exp8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AEIXxg_P9J5w_kK2TA9_ZMz6KN-dEuN1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"

columns = [
    "Pregnancies",
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI",
    "DiabetesPedigreeFunction",
    "Age",
    "Outcome"
]

df = pd.read_csv(url, names=columns)

df.head()

print("Dataset shape:", df.shape)

print("\nDataset information:")
df.info()

print("\nSummary statistics:")
print(df.describe())

features = [
    "Pregnancies",
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI",
    "DiabetesPedigreeFunction",
    "Age"
]

X = df[features].copy()

print("Selected features:")
print(X.columns.tolist())

zero_columns = [
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI"
]

for col in zero_columns:
    print(col, ":", (X[col] == 0).sum())

for col in zero_columns:
    X[col] = X[col].replace(0, np.nan)

for col in zero_columns:
    X[col] = X[col].fillna(X[col].median())

print("Missing values after preprocessing:")
print(X.isnull().sum())

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print("Standardization completed successfully.")
print("Scaled data shape:", X_scaled.shape)

inertia = []

K = range(2, 11)

for k in K:
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

print("Inertia values:")
for k, value in zip(K, inertia):
    print(f"k = {k}: {value:.2f}")

plt.figure(figsize=(8, 6))

plt.plot(K, inertia, marker="o")

plt.xlabel("Number of Clusters (k)")
plt.ylabel("Within-Cluster Sum of Squares (Inertia)")
plt.title("Elbow Method for Optimal k")

plt.xticks(K)
plt.show()

optimal_k = 3

kmeans = KMeans(
    n_clusters=optimal_k,
    random_state=42,
    n_init=10
)

clusters = kmeans.fit_predict(X_scaled)

df["Cluster"] = clusters

print("K-Means clustering completed.")
print("\nCluster counts:")
print(df["Cluster"].value_counts().sort_index())

silhouette = silhouette_score(X_scaled, clusters)

print("Silhouette Score:", silhouette)

silhouette_scores = []

for k in range(2, 11):
    kmeans_temp = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = kmeans_temp.fit_predict(X_scaled)

    score = silhouette_score(X_scaled, labels)
    silhouette_scores.append(score)

print("Silhouette Scores:")
for k, score in zip(range(2, 11), silhouette_scores):
    print(f"k = {k}: {score:.4f}")

plt.figure(figsize=(8, 6))

plt.plot(
    range(2, 11),
    silhouette_scores,
    marker="o"
)

plt.xlabel("Number of Clusters (k)")
plt.ylabel("Silhouette Score")
plt.title("Silhouette Score for Different k Values")

plt.xticks(range(2, 11))
plt.show()

pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_scaled)

print("Original number of features:", X_scaled.shape[1])
print("Reduced number of components:", X_pca.shape[1])

explained_variance = pca.explained_variance_ratio_

print("Explained variance by PC1:", explained_variance[0])
print("Explained variance by PC2:", explained_variance[1])

print("Total explained variance:", explained_variance.sum())

pca_df = pd.DataFrame(
    X_pca,
    columns=["PC1", "PC2"]
)

pca_df["Cluster"] = clusters

pca_df.head()

plt.figure(figsize=(9, 7))

sns.scatterplot(
    data=pca_df,
    x="PC1",
    y="PC2",
    hue="Cluster",
    palette="Set1",
    s=70
)

plt.title("K-Means Clusters Visualized using PCA")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")

plt.show()

cluster_outcome = pd.crosstab(
    df["Cluster"],
    df["Outcome"]
)

cluster_outcome.columns = [
    "Non-Diabetic (0)",
    "Diabetic (1)"
]

print(cluster_outcome)

pca_outcome = pd.DataFrame(
    X_pca,
    columns=["PC1", "PC2"]
)

pca_outcome["Outcome"] = df["Outcome"].values

plt.figure(figsize=(9, 7))

sns.scatterplot(
    data=pca_outcome,
    x="PC1",
    y="PC2",
    hue="Outcome",
    palette="coolwarm",
    s=70
)

plt.title("PCA Visualization by Diabetes Outcome")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")

plt.show()
