# -*- coding: utf-8 -*-
"""exp9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oNOKWmAKu6XWfNITMFMD4VAdNillTWdD
"""

!pip install shap -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import shap

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    brier_score_loss
)

from sklearn.calibration import calibration_curve

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"

columns = [
    "Pregnancies",
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI",
    "DiabetesPedigreeFunction",
    "Age",
    "Outcome"
]

df = pd.read_csv(url, names=columns)

df.head()

print("Dataset shape:", df.shape)

print("\nDataset information:")
df.info()

print("\nOutcome distribution:")
print(df["Outcome"].value_counts())

df_clean = df.copy()

zero_columns = [
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI"
]

for col in zero_columns:
    df_clean[col] = df_clean[col].replace(0, np.nan)

for col in zero_columns:
    df_clean[col] = df_clean[col].fillna(df_clean[col].median())

print("Missing values after preprocessing:")
print(df_clean.isnull().sum())

X = df_clean.drop("Outcome", axis=1)
y = df_clean["Outcome"]

print("Features:", X.shape)
print("Target:", y.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

model = Pipeline([
    ("scaler", StandardScaler()),
    ("logistic", LogisticRegression(random_state=42))
])

model.fit(X_train, y_train)

print("Model trained successfully.")

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Test Accuracy:", accuracy)
print("Test F1-Score:", f1)

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

cv_accuracy = cross_val_score(
    model,
    X_train,
    y_train,
    cv=cv,
    scoring="accuracy"
)

cv_f1 = cross_val_score(
    model,
    X_train,
    y_train,
    cv=cv,
    scoring="f1"
)

print("Cross-Validation Accuracy Scores:")
print(cv_accuracy)

print("\nMean CV Accuracy:", cv_accuracy.mean())

print("\nCross-Validation F1 Scores:")
print(cv_f1)

print("\nMean CV F1-Score:", cv_f1.mean())

brier = brier_score_loss(y_test, y_prob)

print("Brier Score:", brier)

prob_true, prob_pred = calibration_curve(
    y_test,
    y_prob,
    n_bins=10,
    strategy="uniform"
)

plt.figure(figsize=(8, 6))

plt.plot(
    prob_pred,
    prob_true,
    marker="o",
    label="Logistic Regression"
)

plt.plot(
    [0, 1],
    [0, 1],
    linestyle="--",
    label="Perfect Calibration"
)

plt.xlabel("Mean Predicted Probability")
plt.ylabel("Observed Frequency")
plt.title("Calibration Curve")

plt.legend()
plt.show()

scaler = model.named_steps["scaler"]
logistic = model.named_steps["logistic"]

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

explainer = shap.LinearExplainer(
    logistic,
    X_train_scaled
)

shap_values = explainer.shap_values(X_test_scaled)

print("SHAP values calculated successfully.")

shap.summary_plot(
    shap_values,
    X_test_scaled,
    feature_names=X.columns
)

shap.summary_plot(
    shap_values,
    X_test_scaled,
    feature_names=X.columns,
    plot_type="bar"
)

sample_index = 0

print("Actual Outcome:", y_test.iloc[sample_index])
print("Predicted Outcome:", y_pred[sample_index])
print("Predicted Diabetes Probability:", y_prob[sample_index])

shap.force_plot(
    explainer.expected_value,
    shap_values[sample_index],
    X_test_scaled[sample_index],
    feature_names=X.columns,
    matplotlib=True
)

plt.show()

feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Mean Absolute SHAP": np.abs(shap_values).mean(axis=0)
})

feature_importance = feature_importance.sort_values(
    "Mean Absolute SHAP",
    ascending=False
)

print(feature_importance)
